-- VRH: Šifrarnik (login podaci firmi/servisa) — password se čuva ŠIFROVAN.
-- Pokreni ovo u Supabase SQL Editor-u POSLE sql/auth_roles.sql (koristi
-- user_has_view()/user_has_edit() odatle). Idempotentno je.
--
-- ============================================================================
-- OBAVEZAN JEDNOKRATNI KORAK — pre nego što iko unese ijednu šifru
-- ============================================================================
-- Password se šifruje/dešifruje ključem koji se čuva u Supabase Vault-u, NE
-- u ovom fajlu (repo je javan na GitHub-u, sve iz sql/*.sql je vidljivo
-- svima). Pošto pokreneš sve ispod, pokreni JOŠ OVO, JEDNOM, u SQL Editor-u:
--
--   select vault.create_secret(encode(gen_random_bytes(32), 'hex'), 'sifrarnik_key');
--
-- Ova linija generiše nasumičan ključ i odmah ga čuva šifrovano u Vault-u u
-- istom koraku — sirovi ključ se nigde ne ispisuje niti pamti van baze.
-- Ako "vault.create_secret" javi grešku da funkcija ne postoji, prvo uključi
-- Vault: Supabase Dashboard -> Database -> Extensions -> upali "supabase_vault".
--
-- VAŽNO: ta tajna se NIKAD ne sme obrisati niti promeniti posle prvog unosa
-- podataka — ako se izgubi, sve već upisane šifre postaju trajno nečitljive
-- (nema "zaboravljena lozinka" za sam trezor, po dizajnu — inače bi ključ
-- morao negde da postoji van baze, što je tačno ono što želimo da izbegnemo).

create extension if not exists pgcrypto;

create table if not exists sifrarnik (
  id uuid primary key default gen_random_uuid(),
  grupa text,
  ime text not null,
  username text,
  password_encrypted bytea,
  -- write-only: klijent upiše plaintext ovde, trigger ispod ga ODMAH šifruje
  -- u password_encrypted i ovo polje vraća na null u istom pisanju — plain
  -- tekst se nikad ne snima na disk, čak ni privremeno.
  password_plain text,
  link text,
  pristup text,
  komentar text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);

-- ---------- šifrovanje pri upisu ----------

create or replace function sifrarnik_encrypt_password()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key text;
begin
  if NEW.password_plain is not null and NEW.password_plain <> '' then
    select decrypted_secret into v_key from vault.decrypted_secrets where name = 'sifrarnik_key';
    if v_key is null then
      raise exception 'sifrarnik_key nije podešen u Supabase Vault-u — vidi uputstvo na vrhu sql/sifrarnik.sql';
    end if;
    NEW.password_encrypted := pgp_sym_encrypt(NEW.password_plain, v_key);
  end if;
  -- Prazno polje pri izmeni (korisnik nije menjao password) NE dira
  -- postojeći password_encrypted — samo se password_plain uvek čisti.
  NEW.password_plain := null;
  NEW.updated_at := now();
  NEW.updated_by := auth.uid();
  if TG_OP = 'INSERT' then
    NEW.created_by := auth.uid();
  end if;
  return NEW;
end;
$$;

drop trigger if exists sifrarnik_encrypt_password_trigger on sifrarnik;
create trigger sifrarnik_encrypt_password_trigger
before insert or update on sifrarnik
for each row execute function sifrarnik_encrypt_password();

-- ---------- audit log: ko/kad je otključao ili menjao koju šifru ----------

create table if not exists sifrarnik_audit_log (
  id bigint generated by default as identity primary key,
  sifrarnik_id uuid references sifrarnik(id) on delete set null,
  user_id uuid references auth.users(id),
  action text not null, -- 'created' | 'updated' | 'deleted' | 'reveal'
  at timestamptz not null default now()
);

create or replace function sifrarnik_log_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if TG_OP = 'DELETE' then
    insert into sifrarnik_audit_log (sifrarnik_id, user_id, action) values (OLD.id, auth.uid(), 'deleted');
    return OLD;
  elsif TG_OP = 'INSERT' then
    insert into sifrarnik_audit_log (sifrarnik_id, user_id, action) values (NEW.id, auth.uid(), 'created');
    return NEW;
  else
    insert into sifrarnik_audit_log (sifrarnik_id, user_id, action) values (NEW.id, auth.uid(), 'updated');
    return NEW;
  end if;
end;
$$;

drop trigger if exists sifrarnik_log_write_trigger on sifrarnik;
create trigger sifrarnik_log_write_trigger
after insert or update or delete on sifrarnik
for each row execute function sifrarnik_log_write();

-- ---------- otključavanje (dešifrovanje) password-a na zahtev ----------
-- Jedini put kroz koji se password ikad vrati u čitljivom obliku. Frontend
-- (js/app.js) pri običnom učitavanju liste NIKAD ne traži password_encrypted
-- kolonu — samo klik na "Prikaži"/"Kopiraj" konkretnog reda zove ovu
-- funkciju, i svaki poziv se upisuje u sifrarnik_audit_log.

create or replace function reveal_sifrarnik_password(p_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key text;
  v_encrypted bytea;
  v_plain text;
begin
  if not user_has_edit('sifrarnik') then
    raise exception 'Nemate dozvolu za otključavanje šifara';
  end if;

  select password_encrypted into v_encrypted from sifrarnik where id = p_id;
  if v_encrypted is null then
    return null;
  end if;

  select decrypted_secret into v_key from vault.decrypted_secrets where name = 'sifrarnik_key';
  if v_key is null then
    raise exception 'sifrarnik_key nije podešen u Supabase Vault-u — vidi uputstvo na vrhu sql/sifrarnik.sql';
  end if;

  v_plain := pgp_sym_decrypt(v_encrypted, v_key);

  insert into sifrarnik_audit_log (sifrarnik_id, user_id, action) values (p_id, auth.uid(), 'reveal');

  return v_plain;
end;
$$;

grant execute on function reveal_sifrarnik_password(uuid) to authenticated;

-- ---------- RLS ----------
-- "sifrarnik" je nova stranica u istom permission sistemu kao ostale
-- (sql/auth_roles.sql) — dodeljuje se po roli u Podešavanja > Role, isto kao
-- Pregled uređaja/Naplata/itd. Podrazumevano "Bez pristupa" za sve postojeće
-- role dok se ručno ne uključi.

alter table sifrarnik enable row level security;
drop policy if exists "sifrarnik_select" on sifrarnik;
create policy "sifrarnik_select" on sifrarnik
  for select
  using (user_has_view('sifrarnik'));
drop policy if exists "sifrarnik_write" on sifrarnik;
create policy "sifrarnik_write" on sifrarnik
  for all
  using (user_has_edit('sifrarnik'))
  with check (user_has_edit('sifrarnik'));

revoke all on sifrarnik from anon;
grant select, insert, update, delete on sifrarnik to authenticated;

-- Audit log: samo Podešavanja-edit (admin) može da ga čita, i to samo ručno
-- u SQL Editor-u (nema poseban prikaz u appu za sada). Upis ide isključivo
-- kroz SECURITY DEFINER funkcije/trigere iznad (bypass-uju RLS), obični
-- korisnici nemaju direktan insert pristup ovoj tabeli.
alter table sifrarnik_audit_log enable row level security;
drop policy if exists "sifrarnik_audit_log_admin_select" on sifrarnik_audit_log;
create policy "sifrarnik_audit_log_admin_select" on sifrarnik_audit_log
  for select
  using (user_has_edit('settings'));

revoke all on sifrarnik_audit_log from anon, authenticated;
grant select on sifrarnik_audit_log to authenticated;
